name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 17
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          out